// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-BhzY7utpQwxwWAj9TfQ8_iSET2Gx3Hc',
    appId: '1:21452963225:web:8683afc7cc613e3c1aa708',
    messagingSenderId: '21452963225',
    projectId: 'trenpal-d8993',
    authDomain: 'trenpal-d8993.firebaseapp.com',
    storageBucket: 'trenpal-d8993.firebasestorage.app',
    measurementId: 'G-LELD6W8K6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD535V4bbL6VfWu0pzy3P_fdaQc_dY89Tc',
    appId: '1:21452963225:android:baba07416db31e4e1aa708',
    messagingSenderId: '21452963225',
    projectId: 'trenpal-d8993',
    storageBucket: 'trenpal-d8993.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6FgK32iLL_PWLXiTBVvYmYWwxYTNJDYM',
    appId: '1:21452963225:ios:e80be66aa09f4ee11aa708',
    messagingSenderId: '21452963225',
    projectId: 'trenpal-d8993',
    storageBucket: 'trenpal-d8993.firebasestorage.app',
    iosBundleId: 'com.example.trenpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6FgK32iLL_PWLXiTBVvYmYWwxYTNJDYM',
    appId: '1:21452963225:ios:e80be66aa09f4ee11aa708',
    messagingSenderId: '21452963225',
    projectId: 'trenpal-d8993',
    storageBucket: 'trenpal-d8993.firebasestorage.app',
    iosBundleId: 'com.example.trenpal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-BhzY7utpQwxwWAj9TfQ8_iSET2Gx3Hc',
    appId: '1:21452963225:web:249c5eeddeade3a11aa708',
    messagingSenderId: '21452963225',
    projectId: 'trenpal-d8993',
    authDomain: 'trenpal-d8993.firebaseapp.com',
    storageBucket: 'trenpal-d8993.firebasestorage.app',
    measurementId: 'G-LG5NPT3Z1J',
  );
}
